apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: robinnagpal/argo-learning-foo-app:edba18e
          env:
            - name: APP_NAME
              value: foo
---
apiVersion: v1
kind: Service
metadata:
  name: foo-app-service
spec:
  type: NodePort
  selector:
    app: foo-app
  ports:
    - port: 3000
      targetPort: 3000
  template:
    spec:
      containers:
        - image: robinnagpal/argo-learning-foo-app:edba18e
